from draw_functions import *


def rf_rotate_side_up_clockwise(cube, screen):
    draw_left(screen)
    draw_right(screen)
    ver_2(screen)
    ver_3(screen)
    ver_5(screen)
    ver_6(screen)
    ver_8(screen)
    ver_9(screen)
    ver_11(screen)
    ver_12(screen)
    ver_14(screen)
    ver_15(screen)
    ver_17(screen)
    ver_18(screen)
    ver_20(screen)
    ver_21(screen)

def rf_rotate_side_up_counterclockwise(cube, screen):
    draw_left(screen)
    draw_right(screen)
    ver_2(screen)
    ver_3(screen)
    ver_5(screen)
    ver_6(screen)
    ver_8(screen)
    ver_9(screen)
    ver_11(screen)
    ver_12(screen)
    ver_14(screen)
    ver_15(screen)
    ver_17(screen)
    ver_18(screen)
    ver_20(screen)
    ver_21(screen)

def rf_rotate_side_middle_clockwise(cube, screen):
    draw_up(screen)
    draw_left(screen)
    draw_right(screen)
    ver_1(screen)
    ver_3(screen)
    ver_4(screen)
    ver_6(screen)
    ver_7(screen)
    ver_9(screen)
    ver_10(screen)
    ver_12(screen)
    ver_13(screen)
    ver_15(screen)
    ver_16(screen)
    ver_18(screen)
    ver_19(screen)
    ver_21(screen)

def rf_rotate_side_middle_counterclockwise(cube, screen):
    draw_up(screen)
    draw_left(screen)
    draw_right(screen)
    ver_1(screen)
    ver_3(screen)
    ver_4(screen)
    ver_6(screen)
    ver_7(screen)
    ver_9(screen)
    ver_10(screen)
    ver_12(screen)
    ver_13(screen)
    ver_15(screen)
    ver_16(screen)
    ver_18(screen)
    ver_19(screen)
    ver_21(screen)

def rf_rotate_side_down_clockwise(cube, screen):
    draw_up(screen)
    
    left_hor_1(screen)
    left_hor_2(screen)
    left_hor_3(screen)
    left_hor_4(screen)
    left_hor_5(screen)
    left_hor_6(screen)

    right_hor_1(screen)
    right_hor_2(screen)
    right_hor_3(screen)
    right_hor_4(screen)
    right_hor_5(screen)
    right_hor_6(screen)

    ver_1(screen)
    ver_2(screen)
    ver_4(screen)
    ver_5(screen)
    ver_7(screen)
    ver_8(screen)
    ver_10(screen)
    ver_11(screen)
    ver_13(screen)
    ver_14(screen)
    ver_16(screen)
    ver_17(screen)
    ver_19(screen)
    ver_20(screen)

def rf_rotate_side_down_counterclockwise(cube, screen):
    draw_up(screen)
    
    left_hor_1(screen)
    left_hor_2(screen)
    left_hor_3(screen)
    left_hor_4(screen)
    left_hor_5(screen)
    left_hor_6(screen)

    right_hor_1(screen)
    right_hor_2(screen)
    right_hor_3(screen)
    right_hor_4(screen)
    right_hor_5(screen)
    right_hor_6(screen)

    ver_1(screen)
    ver_2(screen)
    ver_4(screen)
    ver_5(screen)
    ver_7(screen)
    ver_8(screen)
    ver_10(screen)
    ver_11(screen)
    ver_13(screen)
    ver_14(screen)
    ver_16(screen)
    ver_17(screen)
    ver_19(screen)
    ver_20(screen)


def rf_rotate_side_left_clockwise(cube, screen):
    up_hor_2(screen)
    up_hor_3(screen)
    up_hor_5(screen)
    up_hor_6(screen)
    up_hor_8(screen)
    up_hor_9(screen)
    up_hor_11(screen)
    up_hor_12(screen)

    up_ver_4(screen)
    up_ver_5(screen)
    up_ver_6(screen)
    up_ver_7(screen)
    up_ver_8(screen)
    up_ver_9(screen)
    up_ver_10(screen)
    up_ver_11(screen)
    up_ver_12(screen)

    right_hor_2(screen)
    right_hor_3(screen)
    right_hor_5(screen)
    right_hor_6(screen)
    right_hor_8(screen)
    right_hor_9(screen)

    ver_13(screen)
    ver_14(screen)
    ver_15(screen)
    ver_16(screen)
    ver_17(screen)
    ver_18(screen)
    ver_19(screen)
    ver_20(screen)
    ver_21(screen)
   
def rf_rotate_side_middle_right_clockwise(cube, screen):
    up_hor_1(screen)
    up_hor_3(screen)
    up_hor_4(screen)
    up_hor_6(screen)
    up_hor_7(screen)
    up_hor_9(screen)
    up_hor_10(screen)
    up_hor_12(screen)

    up_ver_1(screen)
    up_ver_2(screen)
    up_ver_3(screen)
    up_ver_4(screen)
    up_ver_5(screen)
    up_ver_6(screen)
    up_ver_7(screen)
    up_ver_8(screen)
    up_ver_9(screen)
    up_ver_10(screen)
    up_ver_11(screen)
    up_ver_12(screen)

    draw_ver(screen)
    draw_left(screen)

    right_hor_1(screen)
    right_hor_3(screen)
    right_hor_4(screen)
    right_hor_6(screen)
    right_hor_7(screen)
    right_hor_9(screen)

def rf_rotate_side_back_right_clockwise(cube, screen):
    up_hor_1(screen)
    up_hor_2(screen)
    up_hor_4(screen)
    up_hor_5(screen)
    up_hor_7(screen)
    up_hor_8(screen)
    up_hor_10(screen)
    up_hor_11(screen)

    up_ver_1(screen)
    up_ver_2(screen)
    up_ver_3(screen)
    up_ver_4(screen)
    up_ver_5(screen)
    up_ver_6(screen)
    up_ver_7(screen)
    up_ver_8(screen)
    up_ver_9(screen)

    ver_1(screen)
    ver_2(screen)
    ver_3(screen)
    ver_4(screen)
    ver_5(screen)
    ver_6(screen)
    ver_7(screen)
    ver_8(screen)
    ver_9(screen)
    ver_10(screen)
    ver_11(screen)
    ver_12(screen)
    ver_13(screen)
    ver_14(screen)
    ver_15(screen)
    ver_16(screen)
    ver_17(screen)
    ver_18(screen)

    draw_left(screen)

    right_hor_1(screen)
    right_hor_2(screen)
    right_hor_4(screen)
    right_hor_5(screen)
    right_hor_7(screen)
    right_hor_8(screen)

def rf_rotate_side_left_counterclockwise(cube, screen):
    up_hor_2(screen)
    up_hor_3(screen)
    up_hor_5(screen)
    up_hor_6(screen)
    up_hor_8(screen)
    up_hor_9(screen)
    up_hor_11(screen)
    up_hor_12(screen)

    up_ver_4(screen)
    up_ver_5(screen)
    up_ver_6(screen)
    up_ver_7(screen)
    up_ver_8(screen)
    up_ver_9(screen)
    up_ver_10(screen)
    up_ver_11(screen)
    up_ver_12(screen)

    right_hor_2(screen)
    right_hor_3(screen)
    right_hor_5(screen)
    right_hor_6(screen)
    right_hor_8(screen)
    right_hor_9(screen)

    ver_13(screen)
    ver_14(screen)
    ver_15(screen)
    ver_16(screen)
    ver_17(screen)
    ver_18(screen)
    ver_19(screen)
    ver_20(screen)
    ver_21(screen)
   
def rf_rotate_side_middle_right_counterclockwise(cube, screen):
    up_hor_1(screen)
    up_hor_3(screen)
    up_hor_4(screen)
    up_hor_6(screen)
    up_hor_7(screen)
    up_hor_9(screen)
    up_hor_10(screen)
    up_hor_12(screen)

    up_ver_1(screen)
    up_ver_2(screen)
    up_ver_3(screen)
    up_ver_4(screen)
    up_ver_5(screen)
    up_ver_6(screen)
    up_ver_7(screen)
    up_ver_8(screen)
    up_ver_9(screen)
    up_ver_10(screen)
    up_ver_11(screen)
    up_ver_12(screen)

    draw_ver(screen)
    draw_left(screen)

    right_hor_1(screen)
    right_hor_3(screen)
    right_hor_4(screen)
    right_hor_6(screen)
    right_hor_7(screen)
    right_hor_9(screen)

def rf_rotate_side_back_right_counterclockwise(cube, screen):
    up_hor_1(screen)
    up_hor_2(screen)
    up_hor_4(screen)
    up_hor_5(screen)
    up_hor_7(screen)
    up_hor_8(screen)
    up_hor_10(screen)
    up_hor_11(screen)

    up_ver_1(screen)
    up_ver_2(screen)
    up_ver_3(screen)
    up_ver_4(screen)
    up_ver_5(screen)
    up_ver_6(screen)
    up_ver_7(screen)
    up_ver_8(screen)
    up_ver_9(screen)

    ver_1(screen)
    ver_2(screen)
    ver_3(screen)
    ver_4(screen)
    ver_5(screen)
    ver_6(screen)
    ver_7(screen)
    ver_8(screen)
    ver_9(screen)
    ver_10(screen)
    ver_11(screen)
    ver_12(screen)
    ver_13(screen)
    ver_14(screen)
    ver_15(screen)
    ver_16(screen)
    ver_17(screen)
    ver_18(screen)

    draw_left(screen)

    right_hor_1(screen)
    right_hor_2(screen)
    right_hor_4(screen)
    right_hor_5(screen)
    right_hor_7(screen)
    right_hor_8(screen)


def rf_rotate_side_right_clockwise(cube, screen):
    up_hor_1(screen)
    up_hor_2(screen)
    up_hor_3(screen)
    up_hor_4(screen)
    up_hor_5(screen)
    up_hor_6(screen)
    up_hor_7(screen)
    up_hor_8(screen)
    up_hor_9(screen)

    up_ver_1(screen)
    up_ver_2(screen)
    up_ver_4(screen)
    up_ver_5(screen)
    up_ver_7(screen)
    up_ver_8(screen)
    up_ver_10(screen)
    up_ver_11(screen)

    ver_1(screen)
    ver_2(screen)
    ver_3(screen)
    ver_4(screen)
    ver_5(screen)
    ver_6(screen)
    ver_7(screen)
    ver_8(screen)
    ver_9(screen)

    left_hor_1(screen)
    left_hor_2(screen)
    left_hor_4(screen)
    left_hor_5(screen)
    left_hor_7(screen)
    left_hor_8(screen)

def rf_rotate_side_middle_left_clockwise(cube, screen):
    up_hor_1(screen)
    up_hor_2(screen)
    up_hor_3(screen)
    up_hor_4(screen)
    up_hor_5(screen)
    up_hor_6(screen)
    up_hor_7(screen)
    up_hor_8(screen)
    up_hor_9(screen)
    up_hor_10(screen)
    up_hor_11(screen)
    up_hor_12(screen)

    up_ver_1(screen)
    up_ver_3(screen)
    up_ver_4(screen)
    up_ver_6(screen)
    up_ver_7(screen)
    up_ver_9(screen)
    up_ver_10(screen)
    up_ver_12(screen)

    draw_ver(screen)
    draw_right(screen)

    left_hor_1(screen)
    left_hor_3(screen)
    left_hor_4(screen)
    left_hor_6(screen)
    left_hor_7(screen)
    left_hor_9(screen)

def rf_rotate_side_back_left_clockwise(cube, screen):
    up_hor_4(screen)
    up_hor_5(screen)
    up_hor_6(screen)
    up_hor_7(screen)
    up_hor_8(screen)
    up_hor_9(screen)
    up_hor_10(screen)
    up_hor_11(screen)
    up_hor_12(screen)

    up_ver_2(screen)
    up_ver_3(screen)
    up_ver_5(screen)
    up_ver_6(screen)
    up_ver_8(screen)
    up_ver_9(screen)
    up_ver_11(screen)
    up_ver_12(screen)

    left_hor_2(screen)
    left_hor_3(screen)
    left_hor_5(screen)
    left_hor_6(screen)
    left_hor_8(screen)
    left_hor_9(screen)

    draw_right(screen)

    ver_4(screen)
    ver_5(screen)
    ver_6(screen)
    ver_7(screen)
    ver_8(screen)
    ver_9(screen)
    ver_10(screen)
    ver_11(screen)
    ver_12(screen)
    ver_13(screen)
    ver_14(screen)
    ver_15(screen)
    ver_16(screen)
    ver_17(screen)
    ver_18(screen)
    ver_19(screen)
    ver_20(screen)
    ver_21(screen)

def rf_rotate_side_right_counterclockwise(cube, screen):
    up_hor_1(screen)
    up_hor_2(screen)
    up_hor_3(screen)
    up_hor_4(screen)
    up_hor_5(screen)
    up_hor_6(screen)
    up_hor_7(screen)
    up_hor_8(screen)
    up_hor_9(screen)

    up_ver_1(screen)
    up_ver_2(screen)
    up_ver_4(screen)
    up_ver_5(screen)
    up_ver_7(screen)
    up_ver_8(screen)
    up_ver_10(screen)
    up_ver_11(screen)

    ver_1(screen)
    ver_2(screen)
    ver_3(screen)
    ver_4(screen)
    ver_5(screen)
    ver_6(screen)
    ver_7(screen)
    ver_8(screen)
    ver_9(screen)

    left_hor_1(screen)
    left_hor_2(screen)
    left_hor_4(screen)
    left_hor_5(screen)
    left_hor_7(screen)
    left_hor_8(screen)

def rf_rotate_side_middle_left_counterclockwise(cube, screen):
    up_hor_1(screen)
    up_hor_2(screen)
    up_hor_3(screen)
    up_hor_4(screen)
    up_hor_5(screen)
    up_hor_6(screen)
    up_hor_7(screen)
    up_hor_8(screen)
    up_hor_9(screen)
    up_hor_10(screen)
    up_hor_11(screen)
    up_hor_12(screen)

    up_ver_1(screen)
    up_ver_3(screen)
    up_ver_4(screen)
    up_ver_6(screen)
    up_ver_7(screen)
    up_ver_9(screen)
    up_ver_10(screen)
    up_ver_12(screen)

    draw_ver(screen)
    draw_right(screen)

    left_hor_1(screen)
    left_hor_3(screen)
    left_hor_4(screen)
    left_hor_6(screen)
    left_hor_7(screen)
    left_hor_9(screen)

def rf_rotate_side_back_left_counterclockwise(cube, screen):
    up_hor_4(screen)
    up_hor_5(screen)
    up_hor_6(screen)
    up_hor_7(screen)
    up_hor_8(screen)
    up_hor_9(screen)
    up_hor_10(screen)
    up_hor_11(screen)
    up_hor_12(screen)

    up_ver_2(screen)
    up_ver_3(screen)
    up_ver_5(screen)
    up_ver_6(screen)
    up_ver_8(screen)
    up_ver_9(screen)
    up_ver_11(screen)
    up_ver_12(screen)

    left_hor_2(screen)
    left_hor_3(screen)
    left_hor_5(screen)
    left_hor_6(screen)
    left_hor_8(screen)
    left_hor_9(screen)

    draw_right(screen)

    ver_4(screen)
    ver_5(screen)
    ver_6(screen)
    ver_7(screen)
    ver_8(screen)
    ver_9(screen)
    ver_10(screen)
    ver_11(screen)
    ver_12(screen)
    ver_13(screen)
    ver_14(screen)
    ver_15(screen)
    ver_16(screen)
    ver_17(screen)
    ver_18(screen)
    ver_19(screen)
    ver_20(screen)
    ver_21(screen)










